version: '3'

services:

  front:
    image: node
    user: "react_user"
    working_dir: /usr/app
    volumes:
    - ./front/:/usr/app
    ports:
    - '8888:8888'
    command: "npm start"
    depends_on:
    - mongo

  back:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./back/:/home/node/app
    expose:
      - "9999"
    ports:
      - '9999:9999'
    command: "npm start"
    depends_on:
    - mongo

  mongo:
    image: mongo
    restart: always
    ports:
    - '27017:27017'